apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-01
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /k8s/volume/pv-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-02
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /k8s/volume/pv-02
