apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deployment-mariadb
  name: deployment-mariadb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: deployment-mariadb
  type: ClusterIP
status:
  loadBalancer: {}
