apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deployment-prestashop
  name: deployment-prestashop
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deployment-prestashop
  type: NodePort
status:
  loadBalancer: {}
